import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { marked } from 'marked'
import sanitizeHtml from 'sanitize-html'

const rootDir = path.dirname(fileURLToPath(import.meta.url))
const webDir = path.join(rootDir, '..')
const docsDir = path.join(webDir, 'cy-docs', 'docs')
const manifestPath = path.join(rootDir, 'cy-docs-notes.json')
const outDir = path.join(webDir, 'src', 'content', 'generated')
const outFile = path.join(outDir, 'notes.ts')

marked.setOptions({ gfm: true, breaks: false })

const SANITIZE_OPTIONS = {
  allowedTags: [
    ...sanitizeHtml.defaults.allowedTags,
    'h1',
    'h2',
    'img',
    'table',
    'thead',
    'tbody',
    'tr',
    'th',
    'td',
  ],
  allowedAttributes: {
    ...sanitizeHtml.defaults.allowedAttributes,
    a: ['href', 'name', 'target', 'rel'],
    img: ['src', 'alt', 'title'],
  },
  transformTags: {
    a: (tagName, attribs) => ({
      tagName,
      attribs: {
        ...attribs,
        rel: 'noopener noreferrer',
      },
    }),
  },
}

function extractTitle(markdown) {
  const match = markdown.match(/^#{1,2}\s+(.+?)\s*$/m)
  return match ? match[1].trim() : 'Untitled'
}

function stripLeadingTitle(markdown, title) {
  const lines = markdown.replace(/^\uFEFF/, '').split('\n')
  const idx = lines.findIndex((line) => /^#{1,2}\s+/.test(line))
  if (idx === -1) return markdown.trim()
  const heading = lines[idx].replace(/^#{1,2}\s+/, '').trim()
  if (heading !== title) return markdown.trim()
  return lines.slice(idx + 1).join('\n').trim()
}

function plainExcerpt(markdown, limit = 140) {
  const candidates = markdown
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/^>\s?/gm, '')
    .split('\n')
    .map((line) => line.replace(/[*_`[\]()]/g, '').trim())
    .filter((line) => line.length >= 24 && !/^文章[一二三四五六七八九十\d]/.test(line))

  const text = candidates[0] ?? markdown.replace(/[#>*_`[\]()]/g, '').trim()
  if (!text) return ''
  return text.length <= limit ? text : `${text.slice(0, limit - 1)}…`
}

function assertDocsDir() {
  if (!fs.existsSync(docsDir)) {
    console.error(
      '[sync-cy-docs] Missing web/cy-docs/docs. Run: git submodule update --init --recursive',
    )
    process.exit(1)
  }
}

function loadManifest() {
  return JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
}

function buildNote(entry) {
  const sourcePath = path.join(docsDir, entry.file)
  if (!fs.existsSync(sourcePath)) {
    throw new Error(`[sync-cy-docs] Missing source file: ${entry.file}`)
  }

  const raw = fs.readFileSync(sourcePath, 'utf8')
  const title = extractTitle(raw)
  const bodyMarkdown = stripLeadingTitle(raw, title)
  const bodyHtml = sanitizeHtml(marked.parse(bodyMarkdown), SANITIZE_OPTIONS)
  const excerpt = plainExcerpt(bodyMarkdown)

  return {
    slug: entry.slug,
    title,
    date: entry.date,
    excerpt,
    bodyHtml,
  }
}

function emitNotesModule(notes) {
  fs.mkdirSync(outDir, { recursive: true })
  const serialized = notes.map((note) => JSON.stringify(note, null, 2)).join(',\n  ')
  const source = `// Generated by scripts/sync-cy-docs.mjs — do not edit.
import type { Note } from '../note'

export const NOTES: readonly Note[] = [
  ${serialized}
]

export function findNote(slug: string): Note | undefined {
  return NOTES.find((note) => note.slug === slug)
}
`
  fs.writeFileSync(outFile, source)
  console.log(`[sync-cy-docs] Wrote ${notes.length} notes → ${path.relative(webDir, outFile)}`)
}

assertDocsDir()
const notes = loadManifest().map(buildNote)
emitNotesModule(notes)
